// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DateCalendar: typeof import('./../components/timeline/DateCalendar.vue')['default']
    FilterLabel: typeof import('./../components/timeline/FilterLabel.vue')['default']
    MandelbrotSet: typeof import('./../components/mandelbrot-set/MandelbrotSet.vue')['default']
    MandelbrotSetTorz: typeof import('./../components/mandelbrot-set/MandelbrotSetTorz.vue')['default']
    MyLead: typeof import('./../components/MyLead.vue')['default']
    ProfilePic: typeof import('./../components/ProfilePic.vue')['default']
    ProjectFilters: typeof import('./../components/timeline/ProjectFilters.vue')['default']
    ProjectLinks: typeof import('./../components/timeline/ProjectLinks.vue')['default']
    ProjectPictures: typeof import('./../components/timeline/ProjectPictures.vue')['default']
    ProjectPin: typeof import('./../components/timeline/ProjectPin.vue')['default']
    Settings: typeof import('./../components/mandelbrot-set/Settings.vue')['default']
    Tile: typeof import('./../components/mandelbrot-set/Tile.vue')['default']
    TileLink: typeof import('./../components/mandelbrot-set/TileLink.vue')['default']
    TileLinkTorz: typeof import('./../components/mandelbrot-set/TileLinkTorz.vue')['default']
    TileTorz: typeof import('./../components/mandelbrot-set/TileTorz.vue')['default']
    TimelineItem: typeof import('./../components/timeline/TimelineItem.vue')['default']
  }
}

export { }
