// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MandelbrotSet: typeof import('./../components/mandelbrot-set/MandelbrotSet.vue')['default']
    ProfilePic: typeof import('./../components/ProfilePic.vue')['default']
    Tile: typeof import('./../components/mandelbrot-set/Tile.vue')['default']
    TileLink: typeof import('./../components/mandelbrot-set/TileLink.vue')['default']
  }
}

export { }
